spring:
  datasource:
    url: jdbc:postgresql://ec2-52-86-115-245.compute-1.amazonaws.com/d2p70ft1bv6u4c
    username: sohthnduwbipay
    password: 62971a3ff89fb0c590e0253d6871ba2256d678d39233dfd9f41a91eff1ea0246
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4

spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

jwt:
  secret-key: fast-campus.simple_sns_2022_secret_key
  # 30 days
  token.expired-time-ms: 2592000000

spring.redis:
  url: redis://:p8e682aad12b7caf6e8a4d75769964a337be7324cd4634764d238a7c4f53b357e@ec2-44-208-247-66.compute-1.amazonaws.com:22049


spring.kafka:
    bootstrap-servers: b-1.msk-cluster.abcd1234.c2.kafka.ap-northeast-2.amazonaws.com:9092,
      b-2.msk-cluster.abcd1234.c2.kafka.ap-northeast-2.amazonaws.com:9092,
      b-3.msk-cluster.abcd1234.c2.kafka.ap-northeast-2.amazonaws.com:9092
    consumer:
      group-id: notification
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: MANUAL
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: false
    topic:
      notification: your-notification-topic-name